services:
  db:
    image: postgres
    restart: unless-stopped
    env_file: ./.postgres.example.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres
      - ./db/dataset:/docker-entrypoint-initdb.d

  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/frontend

  backend:
    depends_on:
      - db
    build: ./backend
    restart: unless-stopped
    env_file: ./.backend.example.env
    ports:
      - 3001:3001
      - 9299:9299
      - 4983:4983
    volumes:
      - ./backend/src:/backend/src
      - ./backend/package.json:/backend/package.json

volumes:
  db:
